### ISSUE TITLE
[tracking] Monolake Ingress Controller

### ISSUE THREAD

**Issue by goldenrye** [cloudwego/monolake#111]
implement a K8S ingress controller with Monolake

- [ ] Support standard k8s ingress APIs through a small http server to respond to the requests from k8s
- [ ] Support standard k8s IngressClass APIs through the same http server
- [ ] Support k8s ingress controller configurations if we want to add extra annotations
- [ ] Support standard k8s ingress controller installations
